[dependencies]
spdlog = { path = 'external/spdlog' }

[directories]
build = 'build'
include = 'include'
sources = 'src'

[libraries]
lib_dirs = []
libraries = ['crypto']

[project]
compiler = 'clang++'
language = 'cpp'
name = 'zyn'
standard = 'c++17'
version = '2.1.0'
